version: '3'
services:
  dev-db:
    container_name: bookmarks-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmarks
    ports:
      - '5432:5432'
